name: fatiando-tutorials
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.11
    - pip
    - numpy
    - cartopy>=0.20
    - scipy
    - pandas
    - matplotlib==3.8.*
    - jupyter
    - jupyterlab
    - jupyterlab-spellchecker
    - xarray
    - netcdf4
    - pygmt==0.11.*
    - gmt==6.5.*
    - pyproj
    - pykdtree
    - numba
    # Fatiando packages
    - pooch>=1.5.0
    - verde>=1.8.0
    - boule>=0.4.*
    - harmonica>=0.6.*
    - ensaio>=0.5.0
    - jupyter-book
